try to guess a $TMPDIR if none is set

diff --git a/pip-requirements-checker b/pip-requirements-checker
--- a/pip-requirements-checker
+++ b/pip-requirements-checker
@@ -76,7 +76,15 @@ do
   fi
 done
 
-
+# Try to guess a $TMPDIR if none is specified
+if [ "$TMPDIR" = '' ]; then
+  if [ -d '/tmp' ] && [ -w '/tmp' ]; then
+    TMPDIR=/tmp
+  else
+    echo "No \$TMPDIR to place backup in; can't continue"
+    exit 1
+  fi
+fi
 
 
 # =====================================================================
